'use strict';

/**
 * CAPABILITY DEFINITION — SINGLE SOURCE OF TRUTH
 * ===============================================
 * Mọi lệnh CLI mà AI agent được phép dùng đều khai báo ở đây, và CHỈ ở đây.
 *
 * - `playable-shared-kit/ai/CAPABILITIES.json` được sinh ra từ file này.
 * - CLAUDE.md / AGENTS.md / GEMINI.md / .cursorrules / copilot-instructions.md /
 *   SKILL.md / PROJECT_MAP.json đều được RENDER từ file này (không chép tay).
 * - `npm run ai:contract:verify` đối chiếu từng capability với CLI thật;
 *   lệch một flag là fail. Đây là thứ chặn doc drift.
 *
 * KHÔNG sửa lệnh trong file .md — sửa ở đây rồi chạy `npm run ai:sync`.
 *
 * probe:
 *   'help'   -> chạy `<probeCmd> --help` và assert `expect` xuất hiện trong output.
 *               Chỉ dùng cho tool có help KHÔNG gây side-effect.
 *   'static' -> đọc source của tool và assert mỗi flag literal có mặt.
 *               Dùng cho tool chạy ngay khi gọi (không có help an toàn).
 *
 * status: 'ok' | 'partial' | 'broken'
 *   'partial' BẮT BUỘC phải kèm `limits` — agent cần biết tool KHÔNG làm được gì.
 */

const TOOLS = 'playable-shared-kit/tools';

/** @type {Array<Object>} */
const CAPABILITIES = [
  // ─────────────────────────────────────────────────────────── onboarding ──
  {
    id: 'map.generate',
    group: 'onboarding',
    title: 'Sinh bản đồ project cho AI',
    npm: 'npm run ai:map',
    cmd: `node ${TOOLS}/project-map-generator.cjs`,
    args: [],
    optional: ['--stdout'],
    when: 'Bước đầu tiên của mọi task. Thay cho việc quét cây thư mục.',
    outputs: ['PROJECT_MAP.json', 'playable-shared-kit/ai/PROJECT_MAP.json'],
    status: 'ok',
    probe: 'help',
    probeCmd: `node ${TOOLS}/project-map-generator.cjs`,
    expect: ['--stdout'],
  },
  {
    id: 'scene.inspect',
    group: 'onboarding',
    title: 'Xem cây node của scene dạng ASCII gọn',
    npm: 'npm run ai:scene -- <sceneName>',
    cmd: `node ${TOOLS}/scene-inspector.cjs <sceneName>`,
    args: ['<sceneName>'],
    optional: ['--json'],
    when: 'Cần biết cấu trúc scene trước khi sửa node/component.',
    outputs: ['stdout'],
    limits: ['Component script hiện UUID thô, chưa giải ra tên class.'],
    status: 'partial',
    probe: 'help',
    probeCmd: `node ${TOOLS}/scene-inspector.cjs`,
    expect: ['sceneName'],
  },
  {
    id: 'memory.query',
    group: 'onboarding',
    title: 'Tra bộ nhớ công việc để tránh lặp lại bẫy cũ',
    npm: 'npm run memory:query -- <keyword>',
    cmd: `node ${TOOLS}/work-memory.cjs query <keyword>`,
    args: ['<keyword>'],
    optional: [],
    when: 'Trước khi giải một vấn đề nghe quen; sau khi giải xong thì ghi lại.',
    outputs: ['stdout'],
    limits: ['Embedding tắt khi thiếu `sqlite-vec` — recall theo keyword, có thể trả kết quả lệch chủ đề.'],
    status: 'partial',
    probe: 'static',
    expect: ['query'],
    file: `${TOOLS}/work-memory.cjs`,
  },

  // ──────────────────────────────────────────────────────────────── port ──
  {
    id: 'port.prefab',
    group: 'port',
    title: 'Port prefab / mesh / material Unity sang Cocos',
    npm: null,
    cmd: `node ${TOOLS}/unity-cocos-port.cjs port`,
    args: ['--src <unity_prefab_or_dir>', '--out <cocos_prefab_or_dir>'],
    optional: [
      '--unity-root <path>', '--cocos-root <path>', '--report <path>',
      '--overwrite', '--dry-run', '--recursive', '--copy-assets',
      '--convert-fbx-fallback', '--script-mode <mode>', '--layer-map <json>',
    ],
    when: 'Chuyển prefab Unity thành .prefab của Cocos.',
    outputs: ['<out>/*.prefab', '.unity/port-report.csv'],
    limits: [
      'Chậm: đo được ≈140 s/prefab trên project 68k asset meta; chưa có cache, chưa song song.',
      'Shader tuỳ biến KHÔNG được port — xem `shader.convert`.',
      'Luôn đọc report và xử lý mọi dòng `high` trước khi coi là xong.',
    ],
    status: 'partial',
    verify: 'npm run ai:verify',
    probe: 'help',
    probeCmd: `node ${TOOLS}/unity-cocos-port.cjs`,
    expect: ['port', '--src', '--out', '--overwrite', '--dry-run', '--recursive'],
  },
  {
    id: 'port.smart',
    group: 'port',
    title: 'Port cả thư mục Unity (all-in-one)',
    npm: 'npm run port:smart -- --src <unity_dir> --out assets/',
    cmd: `node ${TOOLS}/unity-cocos-port.cjs smart-port`,
    args: ['--src <unity_dir>', '--out assets/'],
    optional: ['--dry-run', '--overwrite', '--report <path>'],
    when: 'Port hàng loạt. Nên chạy `--dry-run` trước để xem report.',
    outputs: ['assets/**', '.unity/port-report.csv'],
    limits: ['Cùng giới hạn tốc độ và shader như `port.prefab`.'],
    status: 'partial',
    verify: 'npm run ai:verify',
    probe: 'help',
    probeCmd: `node ${TOOLS}/unity-cocos-port.cjs`,
    expect: ['smart-port', '--src', '--out'],
  },
  {
    id: 'port.compile',
    group: 'port',
    title: 'Static first-pass C# Unity sang Cocos Creator TypeScript',
    npm: 'npm run port:compile -- --src <csharp_path> --out assets/script/',
    cmd: `node ${TOOLS}/compiler/unity-cs-compiler.cjs`,
    args: ['--src <csharp_file_or_dir>', '--out <ts_dir>'],
    optional: ['--dry-run', '--report <path>', '--runtime-only', '--flat-output', '--verbose'],
    when: 'Port script/logic C# sang TS: AI Agent LUÔN CHẠY LỆNH NÀY TRƯỚC TIÊN để tạo static first pass, sau đó đọc report và refine/polish gameplay semantics.',
    outputs: ['<out>/<relative-source-path>/*.ts', '<report>.json'],
    limits: [
      'Pass nghĩa là parser/emitter và cú pháp TypeScript hợp lệ; KHÔNG xác nhận gameplay semantic equivalence.',
      'Các file có TODO hoặc warning luôn cần AI refine; dùng `--runtime-only` để bỏ Unity Editor code khi port playable runtime.',
      'Mặc định giữ cấu trúc thư mục để tránh ghi đè basename; `--flat-output` chỉ dùng khi đã kiểm tra collision.',
    ],
    status: 'partial',
    verify: 'npm run ai:verify',
    probe: 'static',
    expect: ['--src', '--out', '--dry-run', '--report', '--runtime-only', '--flat-output'],
    file: `${TOOLS}/compiler/unity-cs-compiler.cjs`,
  },
  {
    id: 'port.script',
    group: 'port',
    title: 'Scaffold C# MonoBehaviour sang TypeScript',
    npm: 'npm run port:script -- --src <csharp_path> --out assets/script/',
    cmd: `node ${TOOLS}/unity-cocos-port.cjs scaffold-script`,
    args: ['--src <csharp_file_or_dir>', '--out <ts_dir>'],
    optional: [],
    when: 'Cần khung TS + @property từ script Unity.',
    outputs: ['<out>/*.ts'],
    limits: [
      'CHỈ sinh property và method rỗng — 100% logic phải do agent dịch tay từ file .cs gốc.',
      'Làm phẳng thư mục theo tên class; trùng tên sẽ ghi đè.',
      'Giá trị mặc định C# được chèn nguyên văn, có thể không compile.',
    ],
    status: 'partial',
    verify: 'npm run ai:verify',
    probe: 'help',
    probeCmd: `node ${TOOLS}/unity-cocos-port.cjs`,
    expect: ['scaffold-script', '--src', '--out'],
  },
  {
    id: 'shader.convert',
    group: 'port',
    title: 'Chuyển Unity .shader / .shadergraph sang Cocos .effect',
    npm: null,
    cmd: `node ${TOOLS}/unity-hlsl-to-cocos-effect.cjs convert`,
    args: ['--src <unity.shader>', '--out <assets/effects/X.effect>'],
    optional: ['-m', '--overwrite', '--dry-run', '--shading-model <model>', '--transparent', '--opaque', '--alpha-clip', '--report <path>'],
    when: 'Cần khung .effect + properties + UBO từ shader Unity.',
    outputs: ['<out>', '<out>.meta', '.unity/hlsl-port-report.csv'],
    limits: [
      'KHÔNG dịch thân HLSL. Chỉ sinh khung + properties + UBO, thân shader là template.',
      'Report sẽ ghi `high SHADER_NEEDS_MANUAL_PORT` — agent phải tự viết lại phần tính toán.',
    ],
    status: 'partial',
    verify: 'npm run ai:verify',
    probe: 'help',
    probeCmd: `node ${TOOLS}/unity-hlsl-to-cocos-effect.cjs`,
    expect: ['convert', '--src', '--out', '--shading-model'],
  },
  {
    id: 'shader.batch',
    group: 'port',
    title: 'Chuyển cả thư mục shader',
    npm: null,
    cmd: `node ${TOOLS}/unity-hlsl-to-cocos-effect.cjs batch`,
    args: ['--dir <unity_shader_dir>', '--out-dir <assets/effects>'],
    optional: ['-m', '--overwrite'],
    when: 'Chuyển nhiều shader một lượt.',
    outputs: ['<out-dir>/*.effect', '.unity/hlsl-port-report.csv'],
    limits: ['Cùng giới hạn với `shader.convert`.'],
    status: 'partial',
    probe: 'help',
    probeCmd: `node ${TOOLS}/unity-hlsl-to-cocos-effect.cjs`,
    expect: ['batch', '--dir', '--out-dir'],
  },
  {
    id: 'fbx.strip',
    group: 'port',
    title: 'Gỡ liên kết texture nhúng trong FBX đã import vào Cocos',
    npm: 'npm run fbx:strip -- <file.fbx>',
    cmd: `node ${TOOLS}/strip-fbx-textures.cjs <file.fbx>`,
    args: ['<file.fbx>'],
    optional: [],
    when: 'Sau khi FBX đã nằm trong assets/ của Cocos và có .meta đi kèm.',
    outputs: ['<file.fbx>.meta'],
    limits: [
      'Nhận MỘT file, không nhận thư mục.',
      'Bắt buộc phải có `<file>.fbx.meta` bên cạnh — tức là chỉ chạy được SAU khi Cocos đã import.',
    ],
    status: 'ok',
    probe: 'help',
    probeCmd: `node ${TOOLS}/strip-fbx-textures.cjs`,
    expect: ['fbx'],
  },

  // ────────────────────────────────────────────────────────────── verify ──
  {
    id: 'verify.all',
    group: 'verify',
    title: 'Cổng xác minh bắt buộc: TS, config, asset binding, meta, bundle size',
    npm: 'npm run ai:verify',
    cmd: `node ${TOOLS}/headless-verifier.cjs --json`,
    args: [],
    optional: ['--json'],
    when: 'BẮT BUỘC sau mọi lần sửa code hoặc port. Phải sạch trước khi kết thúc lượt.',
    outputs: ['stdout (JSON khi có --json)'],
    status: 'ok',
    probe: 'help',
    probeCmd: `node ${TOOLS}/headless-verifier.cjs`,
    expect: ['--json'],
  },
  {
    id: 'verify.gc',
    group: 'verify',
    title: 'Lint Zero-GC và quy tắc playable',
    npm: 'npm run ai:lint',
    cmd: `node ${TOOLS}/zero-gc-linter.cjs --json`,
    args: [],
    optional: ['--json'],
    when: 'BẮT BUỘC cùng với `verify.all`.',
    outputs: ['stdout (JSON khi có --json)'],
    status: 'ok',
    probe: 'help',
    probeCmd: `node ${TOOLS}/zero-gc-linter.cjs`,
    expect: ['--json'],
  },

  // ─────────────────────────────────────────────────────────── optimize ──
  {
    id: 'audio.optimize',
    group: 'optimize',
    title: 'Nén audio bằng FFmpeg',
    npm: 'npm run sound:optimize',
    cmd: `node ${TOOLS}/audio-optimizer.cjs`,
    args: [],
    optional: ['--write', '--format <mp3|ogg>', '--doctor'],
    when: 'Khi bundle vượt ngưỡng và audio chiếm tỉ trọng lớn.',
    outputs: ['assets/resources/sound/**'],
    limits: ['Mặc định là dry-run; phải thêm `--write` mới ghi đè.'],
    status: 'ok',
    probe: 'help',
    probeCmd: `node ${TOOLS}/audio-optimizer.cjs`,
    expect: ['--write', '--doctor'],
  },
  {
    id: 'assets.cleanup',
    group: 'optimize',
    title: 'Tìm asset không được tham chiếu',
    npm: 'npm run cleanup:unused',
    cmd: `node ${TOOLS}/unused-asset-cleanup.cjs`,
    args: [],
    optional: ['--delete'],
    when: 'Trước khi build bản cuối, để cắt bundle.',
    outputs: ['stdout'],
    limits: [
      'NGUY HIỂM: asset vừa port nhưng chưa được scene/prefab nào tham chiếu sẽ bị liệt kê là unused.',
      'KHÔNG chạy `--delete` ngay sau khi port.',
    ],
    status: 'partial',
    probe: 'help',
    probeCmd: `node ${TOOLS}/unused-asset-cleanup.cjs`,
    expect: ['--delete'],
  },
  {
    id: 'stats.resources',
    group: 'optimize',
    title: 'Thống kê phân bổ dung lượng asset',
    npm: 'npm run stats',
    cmd: `node ${TOOLS}/resource-stats.cjs`,
    args: [],
    optional: ['--html', '--json', '--doctor'],
    when: 'Khi cần biết thứ gì đang làm bundle phình.',
    outputs: ['stdout / HTML report'],
    status: 'ok',
    probe: 'help',
    probeCmd: `node ${TOOLS}/resource-stats.cjs`,
    expect: ['--json', '--html'],
  },

  // ────────────────────────────────────────────────────── build & deploy ──
  {
    id: 'build.playable',
    group: 'build',
    title: 'Build playable single-file',
    npm: 'npm run build',
    cmd: `node ${TOOLS}/playable-build.cjs build --all`,
    args: [],
    optional: ['--brief <name>', '--parallel', '--jobs <n>', '--sequential', '--aggressive', '--no-clean', '--cocos <path>'],
    when: 'Sau khi verify sạch.',
    outputs: ['build/**/*.html'],
    limits: ['Playable nên dưới 3.5 MB; verifier sẽ cảnh báo khi vượt.'],
    status: 'ok',
    probe: 'static',
    expect: ['build'],
    file: `${TOOLS}/playable-build/playable-cli.cjs`,
  },
  {
    id: 'build.doctor',
    group: 'build',
    title: 'Kiểm tra môi trường build',
    npm: 'npm run doctor',
    cmd: `node ${TOOLS}/playable-build.cjs doctor`,
    args: [],
    optional: [],
    when: 'Khi build lỗi hoặc mới clone repo.',
    outputs: ['stdout'],
    status: 'ok',
    probe: 'static',
    expect: ['doctor'],
    file: `${TOOLS}/playable-build/playable-cli.cjs`,
  },
  {
    id: 'deploy.preview',
    group: 'build',
    title: 'Deploy bản preview + QR cho mobile',
    npm: 'npm run deploy',
    cmd: `node ${TOOLS}/deploy-preview.cjs`,
    args: [],
    optional: ['--build', '--provider <github|netlify|vercel|all>', '--doctor'],
    when: 'Khi cần gửi bản chạy thử cho người khác.',
    outputs: ['URL preview + QR'],
    status: 'ok',
    probe: 'help',
    probeCmd: `node ${TOOLS}/deploy-preview.cjs`,
    expect: ['--provider', '--doctor'],
  },

  // ───────────────────────────────────────────────────────── knowledge ──
  {
    id: 'ai.sync',
    group: 'knowledge',
    title: 'Sinh lại toàn bộ tri thức cho mọi AI agent từ manifest',
    npm: 'npm run ai:sync',
    cmd: `node ${TOOLS}/ai-knowledge-sync.cjs`,
    args: [],
    optional: [],
    when: 'Sau khi sửa `capabilities.def.cjs` hoặc thay đổi tool.',
    outputs: [
      'CLAUDE.md', 'AGENTS.md', 'GEMINI.md', '.cursorrules',
      '.github/copilot-instructions.md', 'playable-shared-kit/ai/CAPABILITIES.json',
      'playable-shared-kit/ai/CORE.md',
    ],
    status: 'ok',
    probe: 'static',
    expect: ['CAPABILITIES'],
    file: `${TOOLS}/ai-knowledge-sync.cjs`,
  },
  {
    id: 'ai.contract',
    group: 'knowledge',
    title: 'Đối chiếu mọi lệnh trong manifest với CLI thật',
    npm: 'npm run ai:contract:verify',
    cmd: `node ${TOOLS}/contract-verify.cjs`,
    args: [],
    optional: ['--json'],
    when: 'Trong CI, và sau khi đổi CLI của bất kỳ tool nào.',
    outputs: ['stdout (exit 1 khi có drift)'],
    status: 'ok',
    probe: 'help',
    probeCmd: `node ${TOOLS}/contract-verify.cjs`,
    expect: ['--json'],
  },
  {
    id: 'memory.remember',
    group: 'knowledge',
    title: 'Ghi lại bẫy / giải pháp mới vào bộ nhớ công việc',
    npm: 'npm run memory:stats',
    cmd: `node ${TOOLS}/work-memory.cjs stats`,
    args: [],
    optional: [],
    when: 'Sau khi giải xong một vấn đề không hiển nhiên.',
    outputs: ['SQLite work-memory'],
    status: 'ok',
    probe: 'static',
    expect: ['stats'],
    file: `${TOOLS}/work-memory.cjs`,
  },
];

/** Nguyên tắc bất biến — mọi agent phải tuân thủ, độc lập với lệnh cụ thể. */
const CORE_RULES = [
  {
    id: 'config-driven',
    rule: 'Mọi tham số gameplay/CTA nằm trong `assets/resources/playable-config.json`, đọc qua `PlayableConfigManager.instance`. Không hardcode trong TS hay trên node của scene.',
  },
  {
    id: 'zero-gc',
    rule: 'Không cấp phát trong `update(dt)`. Khai báo sẵn `Vec3` / `Quat` / `Color` ở module scope và tái sử dụng. Dùng `ObjectPool` cho spawner.',
  },
  {
    id: 'verify-gate',
    rule: 'Sau mọi lần sửa code hoặc port: chạy `npm run ai:verify` và `npm run ai:lint`. Phải sạch trước khi kết thúc lượt trả lời.',
  },
  {
    id: 'canonical-paths',
    rule: 'Script vào `assets/script/`, effect vào `assets/effects/`, config vào `assets/resources/`. Không tự tạo biến thể như `assets/scripts/`.',
  },
  {
    id: 'severity',
    rule: 'Ngữ nghĩa severity trong report: `high` = mất hành vi hoặc mất hình ảnh, phải xử lý; `medium` = cần người quyết định; `low` = ghi chú thông tin. Không bỏ qua `high`.',
  },
  {
    id: 'trust-but-verify',
    rule: 'Tool báo thành công KHÔNG đồng nghĩa kết quả đúng. Luôn mở ít nhất một file sinh ra để đối chiếu với nguồn trước khi kết luận.',
  },
  {
    id: 'meta-files',
    rule: 'Không sửa tay file `.meta`. Luôn đi qua tool hoặc Cocos editor để giữ UUID nhất quán.',
  },
];

module.exports = { CAPABILITIES, CORE_RULES, TOOLS };
