'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
class Texture2D {
 setFilters(a,b){this.filters=[a,b];} setMipFilter(a){this.mip=a;} setWrapMode(...a){this.wrap=a;} setAnisotropy(a){this.aniso=a;}
 reset(info){this.info=info;this.generated=!this.isUsingOfflineMipmaps();this.uploads=[];}
 isUsingOfflineMipmaps(){return false;}
 uploadData(bytes,level){this.uploads.push({bytes:[...bytes],level});}
 destroy(){this.destroyed=true;}
}
const out={};new Function('exports','require',ts.transpileModule(fs.readFileSync(path.join(__dirname,'runtime/UnityImportedTexture.ts'),'utf8'),{compilerOptions:{module:1,target:7}}).outputText)(out,()=>({Texture2D,gfx:{Format:{SRGB8_A8:99},Filter:{NONE:0,POINT:1,LINEAR:2},Address:{WRAP:0,MIRROR:1,CLAMP:2}}}));
test('native mip uploads disable autogenerated replacement and cache lifetime is explicit',()=>{
 const source={width:3,height:3,name:'native',_uuid:'id',getSamplerInfo:()=>({})},cache=new out.UnityImportedTexture();
 const data={schemaVersion:1,srgb:true,textureUuid:'id',mips:[{width:2,height:2,rgba:Buffer.alloc(16,128).toString('base64')},{width:1,height:1,rgba:Buffer.alloc(4,64).toString('base64')}]};
 const t=cache.get(source,data);assert.equal(t.generated,false);assert.equal(t.info.format,99);assert.equal(t.info.mipmapLevel,2);assert.deepEqual(t.uploads.map(x=>x.level),[0,1]);assert.equal(cache.get(source,data),t);cache.destroy();assert.equal(t.destroyed,true);
 assert.throws(()=>cache.get(source,{...data,mips:[data.mips[0],{...data.mips[1],rgba:'AA=='}]}),/byte count/);
 assert.throws(()=>cache.get(source,{...data,mips:[...data.mips,data.mips[1]]}),/Incomplete/);
 assert.throws(()=>cache.get(source,{...data,srgb:false}),/Unsupported/);
});

test('native imported sampler overrides the converted container defaults',()=>{const source={width:3,height:3,name:'converted PNG',_uuid:'id',getSamplerInfo:()=>({minFilter:1,magFilter:1,mipFilter:0})},cache=new out.UnityImportedTexture(),data={schemaVersion:1,srgb:true,textureUuid:'id',mips:[{width:1,height:1,rgba:'AQIDBA=='}],sampler:{filterMode:'Trilinear',wrapU:'Repeat',wrapV:'Clamp',wrapW:'Mirror',anisoLevel:4,mipMapBias:0}};const t=cache.get(source,data);assert.deepEqual(t.filters,[2,2]);assert.deepEqual(t.wrap,[0,2,1]);assert.equal(t.mip,0);assert.equal(t.aniso,4);cache.destroy();assert.throws(()=>cache.get(source,{...data,sampler:{...data.sampler,mipMapBias:1}}),/measured shader/);assert.throws(()=>cache.get(source,{...data,sampler:{...data.sampler,wrapU:'MirrorOnce'}}),/Unsupported/);});
