const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),ts=require('typescript');
const m={exports:{}};new Function('module','exports',ts.transpileModule(fs.readFileSync(path.join(__dirname,'runtime/UnityParticleLightKernel.ts'),'utf8'),{compilerOptions:{module:1}}).outputText)(m,m.exports);
const color=require('./fixtures/particle-light-color-native.json'),range=require('./fixtures/particle-light-range-native.json');
const sha=file=>crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,'fixtures',file),'utf8').replace(/\r\n/g,'\n')).digest('hex');
const base={range:10,intensity:1,color:[1,1,1],rangeMultiplier:1.2,intensityMultiplier:.5,useParticleColor:true,sizeAffectsRange:true,alphaAffectsIntensity:true,maxLights:20};
test('native GPU light fixtures bind portable capture producers and the range prerequisite',()=>{assert.equal(sha('capture-particle-light-color.cs'),color.sourceProbeSha256);assert.equal(sha('capture-particle-light-range.cs'),range.sourceProbeSha256);assert.equal(range.prerequisiteProbeSha256,color.sourceProbeSha256);});
for(const [i,r] of color.rows.filter(r=>r.mode===1).entries())test(`native particle light color ${i}: template choice, linear decode and alpha intensity`,()=>{const out=new Float32Array(8);m.exports.writeUnityParticleLight(out,0,{...base,color:r.templateColor,useParticleColor:r.useColor,alphaAffectsIntensity:r.alphaAffects},{color:{r:r.color[0],g:r.color[1],b:r.color[2],a:r.color[3]},size:{x:1,y:1}},1);for(let c=0;c<3;c++)assert.ok(Math.abs(out[4+c]-r.linearLightColor[c])<1e-6);});
for(const [i,r] of range.rows.entries())test(`native particle light range ${i}: XY geometric size and emitter scale`,()=>{const out=new Float32Array(8);m.exports.writeUnityParticleLight(out,0,{...base,sizeAffectsRange:r.sizeAffects},{color:{r:255,g:255,b:255,a:255},size:{x:r.size[0],y:r.size[1]}},r.scale);assert.ok(Math.abs(out[3]-r.range)<1e-5);});
test('unsupported random light ratios and curves stay explicit',()=>{const {particleLightsContract}=require('./particle-lights-binding');const module={enabled:true,ratio:1,maxLights:20,color:true,range:true,intensity:true,rangeCurve:{minMaxState:0,scalar:1},intensityCurve:{minMaxState:0,scalar:.5}},light={type:2,shadows:0,useColorTemperature:false,range:10,intensity:1,color:[1,1,1]};assert.equal(particleLightsContract({...module,ratio:0},null),null);assert.equal(particleLightsContract(module,light).maxLights,20);assert.throws(()=>particleLightsContract({...module,ratio:.5},light),/ratio/);assert.throws(()=>particleLightsContract({...module,rangeCurve:{minMaxState:1}},light),/multiplier/);});
