'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
const dir=__dirname;const fixture=require('./fixtures/particle-orbit-native.json');
function compile(file,deps={}){const m={exports:{}};new Function('exports','module','require',ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText)(m.exports,m,k=>deps[k]||{});return m.exports;}
const kernel=compile(dir+'/runtime/UnityNoiseKernel.ts'),orbit=compile(dir+'/runtime/UnityParticleOrbit.ts',{'./UnityNoiseKernel':kernel});
const read=p=>JSON.parse(fs.readFileSync(path.join(__dirname,p),'utf8'));
test('native ZXY orbital and radial integration',()=>{for(const row of fixture.kernel){let pos=[1,2,3];const count=Math.ceil(row.dt/.03),dt=row.dt/count,out=new Float64Array(3);for(let i=0;i<count;i++){orbit.orbitalDelta(out,...pos,...row.omega,row.radial,dt);pos=pos.map((x,j)=>x+dt*(out[j]+[.4,.5,.6][j]));}for(let i=0;i<3;i++)assert.ok(Math.abs(pos[i]-row.position[i])<.00001,JSON.stringify({row,pos}));}});
test('source Buff 6 and Buff 1 curves reproduce native matched-birth trajectories',()=>{const motion=fixture.motion;for(const name of ['Buff 6','Buff 1']){const v=fixture.velocity[name];let pos=[1,2,3],max=0;const out=new Float64Array(3);for(const row of motion.filter(r=>r.name===name)){const age=(row.step-1)*.01;orbit.orbitalDelta(out,...pos,...['orbitalX','orbitalY','orbitalZ','radial'].map(k=>kernel.sampleNoiseCurve(v[k],age,0)),.01);pos=pos.map((x,i)=>x+.01*(out[i]+[.4,.5,.6][i]+kernel.sampleNoiseCurve(v[['x','y','z'][i]],age,0)));max=Math.max(max,...pos.map((x,i)=>Math.abs(x-row.position[i])));}assert.ok(max<.0001,name+' maximum error '+max);}});

test('native fixtures retain their capture producer hashes',()=>{const crypto=require('node:crypto');for(const [name,hash] of Object.entries(fixture.sourceProbes))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,'fixtures',name),'utf8').replace(/\r\n/g,'\n')).digest('hex'),hash);});
test('negative radial crossing the emitter origin matches Unity without invented clamping',()=>{for(const row of fixture.negativeRadial){let pos=[.01,.02,.03];const n=Math.ceil(row.dt/.03),dt=row.dt/n,out=new Float64Array(3);for(let i=0;i<n;i++){orbit.orbitalDelta(out,...pos,...row.omega,row.radial,dt);pos=pos.map((x,j)=>x+dt*out[j]);}assert.ok(Math.hypot(...pos.map((x,j)=>x-row.position[j]))<.000001);}});
