'use strict';

const assert = require('node:assert/strict');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const test = require('node:test');

const {
  REQUIRED_SCRIPTS,
  findAbsolutePathTokens,
  inspectPackageScripts,
  normalizeSkillSource,
  parseArgs,
  parseSubmoduleStatus,
} = require('./portable-workflow-doctor.cjs');

test('CLI parses portable options and rejects accidental mutation flags', () => {
  const parsed = parseArgs(['--project', '.', '--json']);
  assert.equal(parsed.project, path.resolve('.'));
  assert.equal(parsed.json, true);
  assert.throws(() => parseArgs(['--write']), error => error.code === 'PORTABLE_DOCTOR_OPTION_INVALID');
});

test('submodule status distinguishes exact, mismatch, uninitialized and conflict', () => {
  const hash = 'a'.repeat(40);
  assert.equal(parseSubmoduleStatus(` ${hash} playable-shared-kit (heads/main)\n`).state, 'exact');
  assert.equal(parseSubmoduleStatus(`+${hash} playable-shared-kit (heads/main)\n`).state, 'mismatch');
  assert.equal(parseSubmoduleStatus(`-${hash} playable-shared-kit\n`).state, 'uninitialized');
  assert.equal(parseSubmoduleStatus(`U${hash} playable-shared-kit\n`).state, 'conflict');
});

test('package script audit detects missing and drifted shared entrypoints', () => {
  const scripts = Object.fromEntries(Object.entries(REQUIRED_SCRIPTS).map(([name, fragment]) => [name, `node playable-shared-kit/tools/${fragment}`]));
  assert.equal(inspectPackageScripts({ scripts }).ok, true);
  scripts['memory:query'] = 'node local-memory.cjs';
  delete scripts['ai:sync'];
  const checked = inspectPackageScripts({ scripts });
  assert.deepEqual(checked.missing, ['ai:sync']);
  assert.equal(checked.mismatched[0].name, 'memory:query');
});

test('regression manifest path audit reports Windows, UNC and file URLs only', () => {
  const result = findAbsolutePathTokens({
    good: 'docs/tape-jam/oracle.json',
    win: 'C:\\temp\\oracle.json',
    unc: '\\\\server\\share\\unity.png',
    url: 'file:///tmp/oracle.json',
    http: 'http://127.0.0.1:7456/',
  });
  assert.deepEqual(result, ['$.win', '$.unc', '$.url']);
});

test('provider skill normalization ignores generated header and generated blocks only', () => {
  const source = '---\nname: demo\n---\n\n# Skill\n<!-- BEGIN:GENERATED:commands -->\n<!-- END:GENERATED:commands -->\nRule.';
  const deployed = '---\nname: demo\n---\n<!-- Generated by `npm run ai:sync` from playable-shared-kit/ai/capabilities.def.cjs. Do not hand-edit commands. -->\n\n# Skill\n<!-- BEGIN:GENERATED:commands -->\nlarge generated table\n<!-- END:GENERATED:commands -->\nRule.';
  assert.equal(normalizeSkillSource(source), normalizeSkillSource(deployed));
  assert.notEqual(normalizeSkillSource(source), normalizeSkillSource(deployed.replace('Rule.', 'Changed rule.')));
});

test('help is read-only and documents every public option', () => {
  const result = spawnSync(process.execPath, [path.join(__dirname, 'portable-workflow-doctor.cjs'), '--help'], { encoding: 'utf8' });
  assert.equal(result.status, 0);
  assert.match(result.stdout, /--project/);
  assert.match(result.stdout, /--json/);
  assert.match(result.stdout, /Read-only/);
});
