'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const test = require('node:test');

const {
  REQUIRED_SCRIPTS,
  findAbsolutePathTokens,
  gitTrackedFiles,
  inspectPackageScripts,
  inspectProjectPortableEvidence,
  normalizeSkillSource,
  parseArgs,
  parseSubmoduleStatus,
} = require('./portable-workflow-doctor.cjs');

function tempDirectory(t, prefix) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), prefix));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  return root;
}

function git(root, args) {
  return spawnSync('git', ['-C', root, ...args], { encoding: 'utf8', windowsHide: true });
}

test('CLI parses portable options and rejects accidental mutation flags', () => {
  const parsed = parseArgs(['--project', '.', '--json']);
  assert.equal(parsed.project, path.resolve('.'));
  assert.equal(parsed.json, true);
  assert.throws(() => parseArgs(['--write']), error => error.code === 'PORTABLE_DOCTOR_OPTION_INVALID');
});

test('submodule status distinguishes exact, mismatch, uninitialized and conflict', () => {
  const hash = 'a'.repeat(40);
  assert.equal(parseSubmoduleStatus(` ${hash} playable-shared-kit (heads/main)\n`).state, 'exact');
  assert.equal(parseSubmoduleStatus(`+${hash} playable-shared-kit (heads/main)\n`).state, 'mismatch');
  assert.equal(parseSubmoduleStatus(`-${hash} playable-shared-kit\n`).state, 'uninitialized');
  assert.equal(parseSubmoduleStatus(`U${hash} playable-shared-kit\n`).state, 'conflict');
});

test('package script audit detects missing and drifted shared entrypoints', () => {
  const scripts = Object.fromEntries(Object.entries(REQUIRED_SCRIPTS).map(([name, fragment]) => [name, `node playable-shared-kit/tools/${fragment}`]));
  assert.equal(inspectPackageScripts({ scripts }).ok, true);
  scripts['memory:query'] = 'node local-memory.cjs';
  delete scripts['ai:sync'];
  const checked = inspectPackageScripts({ scripts });
  assert.deepEqual(checked.missing, ['ai:sync']);
  assert.equal(checked.mismatched[0].name, 'memory:query');
});

test('regression manifest path audit reports Windows, UNC and file URLs only', () => {
  const result = findAbsolutePathTokens({
    good: 'docs/tape-jam/oracle.json',
    win: 'C:\\temp\\oracle.json',
    unc: '\\\\server\\share\\unity.png',
    url: 'file:///tmp/oracle.json',
    http: 'http://127.0.0.1:7456/',
  });
  assert.deepEqual(result, ['$.win', '$.unc', '$.url']);
});

test('provider skill normalization ignores generated header and generated blocks only', () => {
  const source = '---\nname: demo\n---\n\n# Skill\n<!-- BEGIN:GENERATED:commands -->\n<!-- END:GENERATED:commands -->\nRule.';
  const deployed = '---\nname: demo\n---\n<!-- Generated by `npm run ai:sync` from playable-shared-kit/ai/capabilities.def.cjs. Do not hand-edit commands. -->\n\n# Skill\n<!-- BEGIN:GENERATED:commands -->\nlarge generated table\n<!-- END:GENERATED:commands -->\nRule.';
  assert.equal(normalizeSkillSource(source), normalizeSkillSource(deployed));
  assert.notEqual(normalizeSkillSource(source), normalizeSkillSource(deployed.replace('Rule.', 'Changed rule.')));
});

test('tracked-file audit batches all paths into one bounded Git process', () => {
  const calls = [];
  const runner = (file, args) => {
    calls.push({ file, args });
    return { ok: true, stdout: 'package.json\0docs/reference image.png\0', exitCode: 0 };
  };
  const result = gitTrackedFiles('C:\\portable-project', [
    'package.json',
    'docs\\reference image.png',
    'package.json',
  ], runner);
  assert.equal(result.ok, true);
  assert.deepEqual([...result.tracked].sort(), ['docs/reference image.png', 'package.json']);
  assert.equal(calls.length, 1);
  assert.equal(calls[0].file, 'git');
  assert.deepEqual(calls[0].args.slice(0, 6), ['-C', 'C:\\portable-project', 'ls-files', '-z', '--cached', '--']);
  assert.deepEqual(calls[0].args.slice(6), ['package.json', 'docs/reference image.png']);
});

test('setup gitignore template ignores only regenerated port receipts and resume packets', t => {
  const root = tempDirectory(t, 'portable-gitignore-');
  fs.copyFileSync(path.join(__dirname, '..', 'template-config', '.gitignore'), path.join(root, '.gitignore'));
  assert.equal(git(root, ['init', '--quiet']).status, 0);

  const ignored = relative => git(root, ['check-ignore', '--quiet', '--', relative]).status === 0;
  for (const name of ['resume-packet.json', 'regression-receipt.json', 'static-scaffold.receipt.json']) {
    assert.equal(ignored(`.ai/port/${name}`), true, `${name} should be ignored at the default port root`);
    assert.equal(ignored(`.ai/port/harvest-tile/${name}`), true, `${name} should be ignored in a namespaced port root`);
  }
  assert.equal(ignored('.ai/port/harvest-tile/core-gameplay.json'), false);
  assert.equal(ignored('.ai/port/harvest-tile/static-scaffold.wiring.json'), false);
  assert.equal(ignored('.ai/port/core-gameplay.json'), false);
});

test('project portable evidence follows the canonical regression dependency closure', t => {
  const root = tempDirectory(t, 'portable-evidence-');
  const mkdir = relative => fs.mkdirSync(path.join(root, ...relative.split('/')), { recursive: true });
  const write = (relative, content) => {
    const file = path.join(root, ...relative.split('/'));
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
  };
  write('package.json', '{}\n');
  write('package-lock.json', '{}\n');
  write('tools/qa/eval.js', 'true\n');
  write('docs/references/unity.png', 'png');
  write('docs/references/animation-oracle.json', `${JSON.stringify({
    schemaVersion: 1,
    kind: 'unity-animation-curve-oracle',
    completeness: 'complete',
    clipCount: 1,
    clips: [{
      source: 'Assets/Animations/Test.anim',
      sha256: 'a'.repeat(64),
      duration: 0.5,
      loop: false,
      completeness: 'complete',
      tracks: [{ path: 'Root', property: 'scale', animatedChannels: ['y'], channels: {} }],
    }],
  }, null, 2)}\n`);
  const watchFiles = [];
  for (let index = 0; index < 25; index += 1) {
    const relative = `zz-watch/Watch${String(index).padStart(2, '0')}.ts`;
    write(relative, `export const value${index} = ${index};\n`);
    watchFiles.push(relative);
  }
  write('tools/qa/animation.json', `${JSON.stringify({
    url: 'http://127.0.0.1:7456/',
    outputDir: '.unity/preview-checkpoints/test',
    cases: [{
      name: 'curve closure',
      evalFile: 'tools/qa/eval.js',
      requireEvalOk: true,
      referenceImage: 'docs/references/unity.png',
      animationOracle: 'docs/references/animation-oracle.json',
      requiredTrace: ['start', 'complete'],
      requiredEvalMetrics: {
        crossAxisMaxError: { max: 0.02 },
        curveExtremaMaxError: { max: 0.1 },
        singleShotPhaseCountError: { max: 0 },
        timingMaxErrorMs: { max: 100 },
        oracleClipCount: { min: 1 },
      },
    }],
  }, null, 2)}\n`);
  write('tools/port-regressions.json', `${JSON.stringify({
    schemaVersion: 1,
    kind: 'cc-playable-port-regression-registry',
    requiredRisks: ['animation-curve-fidelity'],
    suites: [{
      id: 'animation-closure',
      risks: ['animation-curve-fidelity'],
      mandatory: true,
      runs: 1,
      matrix: 'tools/qa/animation.json',
      watchFiles,
    }],
  }, null, 2)}\n`);
  mkdir('assets');

  assert.equal(git(root, ['init', '--quiet']).status, 0);
  assert.equal(git(root, ['add', '--', 'package.json', 'package-lock.json', 'tools/port-regressions.json']).status, 0);
  const incomplete = inspectProjectPortableEvidence(root);
  assert.equal(incomplete.ok, false);
  assert.ok(incomplete.closureFileCount > 25);
  assert.ok(incomplete.untrackedCount > 20);
  assert.ok(incomplete.untracked.length > 0 && incomplete.untracked.length <= 20);
  assert.equal(incomplete.diagnosticsTruncated, true);
  assert.ok(incomplete.untracked.includes('docs/references/animation-oracle.json'));
  assert.ok(incomplete.untracked.includes('docs/references/unity.png'));

  assert.equal(git(root, ['add', '--all']).status, 0);
  const complete = inspectProjectPortableEvidence(root);
  assert.equal(complete.ok, true);
  assert.equal(complete.untrackedCount, 0);
  assert.equal(complete.missingCount, 0);

  fs.rmSync(path.join(root, 'docs', 'references', 'animation-oracle.json'));
  const missingDependency = inspectProjectPortableEvidence(root);
  assert.equal(missingDependency.ok, false);
  assert.equal(missingDependency.registryError.code, 'REGRESSION_PATH_MISSING');
});

test('help is read-only and documents every public option', () => {
  const result = spawnSync(process.execPath, [path.join(__dirname, 'portable-workflow-doctor.cjs'), '--help'], { encoding: 'utf8' });
  assert.equal(result.status, 0);
  assert.match(result.stdout, /--project/);
  assert.match(result.stdout, /--json/);
  assert.match(result.stdout, /Read-only/);
});
